global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "spring-boot-ventas"
    metrics_path: "/backend-ventas/actuator/prometheus"
    static_configs:
      - targets: ["laboratorio-academy-alb-2026428119.us-east-1.elb.amazonaws.com"]
        labels:
          application: "ventas"

  - job_name: "spring-boot-despachos"
    metrics_path: "/backend-despachos/actuator/prometheus"
    static_configs:
      - targets: ["laboratorio-academy-alb-2026428119.us-east-1.elb.amazonaws.com"]
        labels:
          application: "despachos"
